### ISSUE TITLE
With oldest first settings, comment just posted can be found with difficulty

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/advanced_comments#1]
Using advanced_comments_v4.0.1, Elgg3.0.1, php7x and in the plugin settings I have 
Comments order : oldest first (this is the most common order used in forums, blogs, social nets etc)
and Comment limit : 50 (or 100)
Now when an user posts a comment (suppose he is the 4oth or 89th comment-or) he expects that, after posting the comment, he will be automatically scrolled to his comment. This is the expected default behavior. However, he only sees the first one or two comments, and to find the comment he has just posted he has to scroll, scroll and search for his comment.

In Elgg org itself, comments are set as oldest first, and the user is taken to the comment he just posted.

**Comment by jdalsem** [comment]
This setting has been moved to Elgg core. The core behaviour is as requested.
