### ISSUE TITLE
UI : for the first and second comment makers, comment box behaves differently

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/advanced_comments#2]
UI interface : When the user is the first one to post a comment he sees an open comment box. But if he is the second or third or fourth etc, he has to click a button to open the comment box. Can there please be an admin option in this plugin to keep the comment box open always ? I understand that this is the default design in Elgg 3.01. - what I am intending is that let this plugin over-ride that and let the site admin have the option to keep it open always, if he wants so.
Thanks.
PS: Also, if the first person comes again after some 15 or 20 comments, he will look for the comment box but not find it again.

**Comment by jdalsem** [comment]
This behaviour is now a setting in Elgg core.
