### ISSUE TITLE
UI : Append the comment box always at the end of comments. 

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/advanced_comments#3]
UI : Append the comment box always at the end of comments. Just as in Elgg org now and probably previous Elgg. This helps : for example : I am reading a blog post or a discussion, and then I read some 40 or 50 comments in a page, and then after reading all this I want to make my own additions in the form of a comment. Expected behavior : I will find a comment box at the end of all comments. But now in Elgg 3.0.1 I will have to scroll, scroll back (up) again and then also there will be no comment box but a button to click which will open the comment box. My suggestion: let this plugin take care of that so that admin can set (if he wants) an open comment box at the end of all comments (just as in Elgg org now). Thanks.

**Comment by daniyaree** [comment]
+1 for enhancement. Can we have this "feature" now? Although I would like to add this is not a feature or enhancement request but just asking what is already in Elgg 2x and Elgg org at present.  Many thanks @jdalsem

**Comment by jdalsem** [comment]
This plugin will not receive any more new features. If current Elgg 4 behaviour is not as you want, please report the wish there
